update ft-util

diff --git a/ft-util/ft_util_bak-cleaner b/ft-util/ft_util_bak-cleaner
--- a/ft-util/ft_util_bak-cleaner
+++ b/ft-util/ft_util_bak-cleaner
@@ -4,10 +4,14 @@ source "$(dirname "$0")/ft_util_inc_var"
 
 $S_LOG -s debug -d $S_NAME "Cleaning start ${1}"
 
-if [ -z "${1}" ] ; then exit ; fi  
+if [ -d "${1}" ] ; then
+    find ${1}* -type f -mtime +7 -name '*.bak' -delete -print | $S_LOG -s debug -d $S_NAME -d "deleted" -i
+    returncode=$? # store the exit code of the command
+elif [ -f "${1}" ] ; then
+    find ${1}* -maxdepth 0 -type f -mtime +7 -name '*.bak' -delete -print | $S_LOG -s debug -d $S_NAME -d "deleted" -i
+    returncode=$? # store the exit code of the command
+fi
 
-find ${1}* -maxdepth 0 -type f -mtime +7 -name '*.bak' -delete -print | $S_LOG -d $S_NAME -d -i
-returncode=$? # store the exit code of the command
 # ls -al ${1}*
 
-$S_LOG -d $S_NAME -d ${1} "cleaning bak exited with code $returncode"
+$S_LOG -s debug -d $S_NAME -d ${1} "cleaning bak exited with code $returncode"
diff --git a/ft-util/ft_util_file-deploy b/ft-util/ft_util_file-deploy
--- a/ft-util/ft_util_file-deploy
+++ b/ft-util/ft_util_file-deploy
@@ -1,79 +1,103 @@
 #!/bin/bash
 
-source "$(dirname "$0")/ft_util_inc_var"
+source "$(dirname "$0"})/ft_util_inc_var"
 
-if [ -z "$1" ] || [ -z "$2" ]
-then
-    $S_LOG -s err -d $S_NAME "Needed variable SOURCE and TARGET are missing. Cannot do file deploy! SOURCE=$1 TARGET=$2 OPTION=$3"
+if [ -z "$1" ] || [ -z "$2" ]; then
+    $S_LOG -s crit -d $S_NAME "Needed variable path_src and path_tgt are missing. Cannot do file deploy! path_src=$1 path_tgt=$2 file_deploy_opts=$3"
     exit 1
-else
-    SOURCE=$1
-    SOURCE_NICE="${SOURCE/#$(dirname "$S_DIR_PATH")\//}" # this will shorten the SOURCE string in order to create less text in logs (note, it will only shorten if the path is in the same ../ dir as this script)
-    TARGET=$2
-    OPTION=$3
 fi
 
-
 #############################
-## BACKUP FILES
+## Functions
 #############################
 
-backup () {    
-    cp "$1" "$1.$(date +\%Y\%m\%d\-\%H\%M\%S).bak"
-    $S_LOG -s debug -d $S_NAME -d "$1" "backup of $1"   
+function backup_file() {
+    if [ -f "$*.${bkp_suffix}" ]; then
+        $S_LOG -s debug -d "${S_NAME}|${path_src_nice}" "Backup skipped of $* > $*.${bkp_suffix}"
+    elif [ ! -f "$*" ]; then
+        $S_LOG -s debug -d "${S_NAME}|${path_src_nice}" "Backup skipped of $* (new file)"
+    else
+        cp "$*" "$*.${bkp_suffix}"
+        $S_LOG -s debug -d "${S_NAME}|${path_src_nice}" "Backup done of $* > $*.${bkp_suffix}"
+    fi
 }
+export -f backup_file
 
-if [ -d "$TARGET" ]
-then
-    for file in ${TARGET%/}/*; do
-        [ -f "$file" ] || break
-        [ "${file##*.}" != "bak" ] || continue # only process files with the same ext than the source    
-        [[ $OPTION == *"NO-BACKUP"* ]] || backup $file
-    done
-elif [ -f "$TARGET" ] 
-then
-    [[ $OPTION == *"NO-BACKUP"* ]] || backup $TARGET
-fi
-
+function compare_file() {
+    if [ -f "$1" ]; then
+        diff --unified=0 "$1" "$2"
+    else
+        echo "no diff on new file: ${2}"
+    fi
+}
+export -f compare_file
 
 #############################
-## DEPLOY FILES
+## Variables
 #############################
 
-returncode=255 
+path_src=$1
+path_src_nice="${path_src/#$(dirname "${S_DIR_PATH}")\//}" # this will shorten the path_src string in order to create less text in logs (note, it will only shorten if the path is in the same ../ dir as this script)
+path_tgt=$2
 
-if [ -d "${TARGET}" ]
-then
-    
-    find "${TARGET%/}/" -type f ! -name '*.bak' -delete 2> >($S_LOG -s err -d $S_NAME -d "$SOURCE_NICE" -i) > >($S_LOG -d $S_NAME -d "$SOURCE_NICE" -i)
-    returncode=$?
-    $S_LOG -s $returncode -d $S_NAME -d "$SOURCE_NICE" "delete existing files exited with code $returncode"
+# Grab options
+if [[ "${3}" == *"NO-BACKUP"* ]]; then opt_backup=false; else opt_backup=true; fi
+if [[ "${3}" == *"NO-COMPARE"* ]]; then opt_compare=false; else opt_compare=true; fi
 
-    cp -R "${SOURCE%/}/." "${TARGET%/}/" 2> >($S_LOG -s err -d $S_NAME -d "$SOURCE_NICE" -i) > >($S_LOG -d $S_NAME -d "$SOURCE_NICE" -i)
+# Backup suffix is the start date of the parent PID... which is gonna be the same if you use this script several time, hence you can do compare...
+# Exemple: in a script you deploy the folder bin then a file 123.sh inside of bin... on the next run 123.sh will be deleted when you redeploy bin files... but will be redeployed AND compared because the backup prefix will be the same
+ppid_age_date=$(ps -olstart= $PPID)              # Get start date of parent PID
+ppid_age_epoch=$(date +%s -d "${ppid_age_date}") # Convert start date to epoch date
+bkp_suffix=$(date +"%Y%m%d-%H%M%S" -d@${ppid_age_epoch}).bak
+$S_LOG -s debug -d "${S_NAME}|${path_src_nice}" "bkp_suffix=${bkp_suffix}"
+
+#############################
+## Deploy file(s)
+#############################
+
+returncode=255
+if [ -d "${path_tgt}" ]; then
+
+    # Backup files
+    if [ "$opt_backup" = true ]; then
+        find "${path_tgt%/}/" -type f ! -name '*.bak' | while read file; do backup_file "${file}"; done
+    fi
+
+    # Delete all the files inside the destination dir (excluding bak)
+    find "${path_tgt%/}/" -type f ! -name '*.bak' -delete 2> >($S_LOG -s err -d "${S_NAME}|${path_src_nice}" -i) > >($S_LOG -d "${S_NAME}|${path_src_nice}" -i)
     returncode=$?
+    $S_LOG -s debug -d "${S_NAME}|${path_src_nice}" "Delete existing files returned EXIT_CODE=$returncode"
+
+    # Copy dir
+    cp -R "${path_src%/}/." "${path_tgt%/}/" 2> >($S_LOG -s err -d "${S_NAME}|${path_src_nice}" -i) > >($S_LOG -d "${S_NAME}|${path_src_nice}" -i)
+    returncode=$?
+
+    # Compare
+    if [ "$opt_backup" = true ]; then
+        if [ "$opt_compare" = true ]; then
+            find "${path_src%/}/" -type f ! -name '*.bak' -exec bash -c "p=\"{}\" ; p=\"${path_tgt%/}\${p#${path_src%/}}\" ; compare_file \"\${p}.${bkp_suffix}\" \"\${p}\"" \; | $S_LOG -s warn -d "${S_NAME}|${path_src_nice}|diff" -i
+        fi
+        $S_DIR_PATH/ft_util_bak-cleaner "${path_tgt%/}/" # Cleanup backup files
+    fi
 
 else
-    [ -d "$(dirname "$TARGET")" ] || mkdir -p "$(dirname "$TARGET")"
-    cp -p "$SOURCE" "$TARGET" 2> >($S_LOG -s err -d $S_NAME -d "$SOURCE_NICE" -i) > >($S_LOG -d $S_NAME -d "$SOURCE_NICE" -i)
+    if [ "$opt_backup" = true ]; then backup_file ${path_tgt}; fi # Backup file
+
+    # Create dir if missing
+    path_tgt_d=$(dirname "${path_tgt}")
+    [ -d "${path_tgt_d}" ] || mkdir -p "${path_tgt_d}"
+
+    # Copy file
+    cp -p "${path_src}" "${path_tgt}" 2> >($S_LOG -s err -d "${S_NAME}|${path_src_nice}" -i) > >($S_LOG -d "${S_NAME}|${path_src_nice}" -i)
     returncode=$? # store the exit code of the command
 
-fi
-$S_LOG -s $returncode -d $S_NAME -d "$SOURCE_NICE" "transfer exited with code $returncode"
-
-
-#############################
-#############################
-## CLEANUP BIN BAK FILES
-#############################
-#############################
-
-if [[ ! $OPTION == *"NO-BACKUP"* ]]
-then
-    if [ -d "${TARGET}" ] 
-    then
-        $S_DIR_PATH/ft_util_bak-cleaner "${TARGET%/}/"
-    elif [ -f "${TARGET}" ] 
-    then
-        $S_DIR_PATH/ft_util_bak-cleaner "${TARGET}"
+    # Compare
+    if [ "$opt_backup" = true ]; then
+        if [ "$opt_compare" = true ]; then
+            compare_file "${path_tgt}.${bkp_suffix}" "${path_tgt}" | $S_LOG -s warn -d "${S_NAME}|${path_src_nice}|diff" -i
+        fi
+        $S_DIR_PATH/ft_util_bak-cleaner "${path_tgt}" # Cleanup backup files
     fi
+
 fi
+$S_LOG -s $returncode -d "${S_NAME}|${path_src_nice}" "Transfer returned EXIT_CODE=$returncode"
diff --git a/ft-util/ft_util_log b/ft-util/ft_util_log
--- a/ft-util/ft_util_log
+++ b/ft-util/ft_util_log
@@ -3,8 +3,7 @@
 declare -a arrayData
 declare -a pathArray
 
-usage()
-{
+usage() {
     echo -e "\nUsage: $0 \
 ([-p <logfile_path>] \
 [-s <alert|crit|err|warn|info|debug>] \
@@ -22,90 +21,84 @@ usage()
 
 while getopts "ip::s::d::" o; do
     case "${o}" in
-        i)
-            acceptStdin=true
+    i)
+        acceptStdin=true
+        ;;
+    p)
+        if [ ! -d "$(dirname "${OPTARG}")" ]; then
+            echo -e "\nft_util_log : Incorrect \$LOG_FILE path (folder missing): \"${pathArray[k]}\"\n" 1>&2
+        else
+            pathArray+=("${OPTARG}")
+        fi
+        ;;
+    s)
+        case ${OPTARG} in
+        alert | \
+            crit | \
+            err | \
+            warn | \
+            info)
+            s=${OPTARG}
             ;;
-        p)
-            if [ ! -d "$(dirname "${OPTARG}")" ] 
-            then
-                echo -e  "\nft_util_log : Incorrect \$LOG_FILE path (folder missing): \"${pathArray[k]}\"\n" 1>&2;
-            else
-                pathArray+=("${OPTARG}")
-            fi
-            ;;
-        s)
-            case ${OPTARG} in
-                alert|\
-                crit|\
-                err|\
-                warn|\
-                info)
-                    s=${OPTARG}
-                    ;;
 
-                debug)
-                    if [ "$LOG_DEBUG" = true ]; then s=${OPTARG}; else exit 0; fi 
-                    ;;
-
-                2[0-5][0-9]|1[0-9][0-9]|[1-9][0-9]|[1-9])
-                    s=err
-                    ;;
-                
-                0)
-                    s=info
-                    ;;
-
-                *)
-                    echo -e  "\nft_util_log : Incorrect severity ${OPTARG}\nAvailable alert|crit|err|warn|info|debug\n" 1>&2;
-                    usage
-                    ;;
-            esac
+        debug)
+            if [ "$LOG_DEBUG" = true ]; then s=${OPTARG}; else exit 0; fi
             ;;
-        d)
-            IFSx=$IFS
-            IFS='|'
-            for arg in $OPTARG
-            do
-                arrayData+=("${arg}")
-            done        
-            IFS=$IFSx
+
+        2[0-5][0-9] | 1[0-9][0-9] | [1-9][0-9] | [1-9])
+            s=err
             ;;
+
+        0)
+            s=info
+            ;;
+
         *)
+            echo -e "\nft_util_log : Incorrect severity ${OPTARG}\nAvailable alert|crit|err|warn|info|debug\n" 1>&2
             usage
             ;;
+        esac
+        ;;
+    d)
+        IFSx=$IFS
+        IFS='|'
+        for arg in $OPTARG; do
+            arrayData+=("${arg}")
+        done
+        IFS=$IFSx
+        ;;
+    *)
+        usage
+        ;;
     esac
     [[ $acceptStdin ]] && break
 done
 
 shift "$((OPTIND - 1))"
 
-echo_log () { 
-    
-    
-    if [ -n "${log_msg}" ]
-    then
+echo_log() {
+
+    if [ -n "${log_msg}" ]; then
         timestamp="$(date +\%Y-\%m-\%d\ \%H:\%M:\%S)"
-        
+
         # Check if terminal support colors
-        if command -v tput >/dev/null
-        then
+        if command -v tput >/dev/null; then
             term_colors=$(tput colors -T $TERM 2>/dev/null)
         else
             term_colors=2
         fi
 
-        # First output to stdout with or formatting formatting 
-        if [ -n "${term_colors}" ] && [ $term_colors -ge 8 ]
-        then
+        # First output to stdout with or formatting formatting
+        if [ -n "${term_colors}" ] && [ $term_colors -ge 8 ]; then
             # Let's put some color
             # https://misc.flogisoft.com/bash/tip_colors_and_formatting
             case ${s} in
-                alert) color="\e[41;93m" ;;
-                crit) color="\e[41m" ;;
-                err) color="\e[91m" ;;
-                warn) color="\e[33m" ;;
-                info) color="\e[94m" ;;
-                debug) color="\e[92m" ;;
+            alert) color="\e[41;93m" ;;
+            crit) color="\e[41m" ;;
+            err) color="\e[91m" ;;
+            warn) color="\e[33m" ;;
+            info) color="\e[94m" ;;
+            debug) color="\e[92m" ;;
             esac
 
             echo -e "${color}${timestamp} ||\e[7m ${s} \e[27m|${data}|\e[0m ${log_msg}"
@@ -114,50 +107,41 @@ echo_log () {
         fi
 
         # Output to file(s)
-        for f in ${pathArray[@]}
-        do
-            echo -e "${timestamp} || ${s} |${data}| ${log_msg}" >> "${f}"
+        for f in ${pathArray[@]}; do
+            echo -e "${timestamp} || ${s} |${data}| ${log_msg}" >>"${f}"
         done
     fi
 }
 
-if [ -z ${s} ]
-then 
+if [ -z ${s} ]; then
     s="info"
 fi
 
-if [[ ${#pathArray[@]} = 0 ]]
-then
-    pathArray=($LOG_FILE) # load the variable in an array
-    for k in ${!pathArray[@]} # check path
-    do 
-        if [ ! -d "$(dirname "${pathArray[k]}")" ] 
-        then
-            echo -e  "\nft_util_log : Incorrect \$LOG_FILE path (folder missing): ${pathArray[k]}\n" 1>&2;
+if [[ ${#pathArray[@]} = 0 ]]; then
+    pathArray=($LOG_FILE)         # load the variable in an array
+    for k in ${!pathArray[@]}; do # check path
+        if [ ! -d "$(dirname "${pathArray[k]}")" ]; then
+            echo -e "\nft_util_log : Incorrect \$LOG_FILE path (folder missing): ${pathArray[k]}\n" 1>&2
             unset pathArray[$k]
         fi
     done
 
-    if [[ ${#pathArray[@]} = 0 ]]  # exit if there are still no path in the array
-    then
-        echo -e "\nft_util_log :  No log file path found." 1>&2; usage;        
+    if [[ ${#pathArray[@]} = 0 ]]; then # exit if there are still no path in the array
+        echo -e "\nft_util_log :  No log file path found." 1>&2
+        usage
     fi
 fi
 
-for i in ${!arrayData[@]}
-do
+for i in ${!arrayData[@]}; do
     data="$data ${arrayData[i]} |"
 done
 
-if [ ! -t 0 ] && [[ $acceptStdin ]] # check if STDIN is open and loop it
-then
-    while read line
-    do
+if [ ! -t 0 ] && [[ $acceptStdin ]]; then # check if STDIN is open and loop it
+    while read line; do
         log_msg="${line}"
         echo_log
     done <&0
-elif [ -n "$*" ] # check if normal argument input
-then
+elif [ -n "$*" ]; then # check if normal argument input
     log_msg="$*"
     echo_log
 fi
diff --git a/ft-util/ft_util_pkg b/ft-util/ft_util_pkg
--- a/ft-util/ft_util_pkg
+++ b/ft-util/ft_util_pkg
@@ -4,25 +4,23 @@ source "$(dirname "$0")/ft_util_inc_var"
 
 while getopts "iu" o; do
     case "${o}" in
-        i)
-            install=true
-            ;;
-        u)
-            update=true        
-            ;;
+    i)
+        install=true
+        ;;
+    u)
+        update=true
+        ;;
     esac
 done
 
 shift "$((OPTIND - 1))"
 
-PKG_ARR=( "$@" )
+pkg_arr=("$@")
 
-if [ "$update" = true ]
-then
+if [ "$update" = true ]; then
     $S_LOG -d $S_NAME "Package list update"
     apt update &>/dev/null
-    if [ $? != "0" ]
-    then
+    if [ $? != "0" ]; then
         $S_LOG -s crit -d $S_NAME "Error while getting package list update."
     else
         $S_LOG -d $S_NAME "Successful package list update."
@@ -30,41 +28,38 @@ then
 fi
 
 # This var will increment for each pkg not found BUT will decrement if the package is successfully installed
-NOT_INSTALLED=0
+not_installed=0
 
-for PKG in "${PKG_ARR[@]}"
-do
-    PKG_OK=$(dpkg-query -W --showformat='${Status}\n' $PKG 2>/dev/null | grep "install ok installed")
-    if [ "" = "$PKG_OK" ]; then        
-        let NOT_INSTALLED++
+for pkg in "${pkg_arr[@]}"; do
+    pkg_ok=$(dpkg-query -W --showformat='${Status}\n' $pkg 2>/dev/null | grep "install ok installed")
+    if [ "" = "$pkg_ok" ]; then
+        let not_installed++
 
-        if [ "$install" = true ]
-        then
-            $S_LOG -s warn -d $S_NAME -d "$PKG" "Missing needed package "$PKG". Setting up $PKG."
-            
+        if [ "$install" = true ]; then
+            $S_LOG -s warn -d $S_NAME -d "$pkg" "Missing needed package "$pkg". Setting up $pkg."
+
             # https://linuxhint.com/debian_frontend_noninteractive/
             # https://askubuntu.com/a/668859
             # DEBIAN_FRONTEND=noninteractive \
             #     apt-get -qq install \
             #     -o Dpkg::Options::="--force-confnew" \
             #     -o Dpkg::Use-Pty=0 \
-            #     $PKG \
-            #     2> >($S_LOG -s err -d $S_NAME -d "apt-get" -d "$PKG" -i) > >($S_LOG -d $S_NAME -d "apt-get" -d "$PKG" -i)        
-            
+            #     $pkg \
+            #     2> >($S_LOG -s err -d $S_NAME -d "apt-get" -d "$pkg" -i) > >($S_LOG -d $S_NAME -d "apt-get" -d "$pkg" -i)
+
             # https://peteris.rocks/blog/quiet-and-unattended-installation-with-apt-get/
-            DEBIAN_FRONTEND=noninteractive apt-get install -qq $PKG < /dev/null > /dev/null
-            
+            DEBIAN_FRONTEND=noninteractive apt-get install -qq $pkg </dev/null >/dev/null
+
             ERR=$? # store the exit code of the command
 
-            if [ $ERR != "0" ]
-            then
-                $S_LOG -s crit -d $S_NAME -d "$PKG" "Failed to install needed packages ("$PKG"). Please fix it and re-run the script."
+            if [ $ERR != "0" ]; then
+                $S_LOG -s crit -d $S_NAME -d "$pkg" "Failed to install needed packages ("$pkg"). Please fix it and re-run the script."
             else
-                let NOT_INSTALLED--
-                $S_LOG -d $S_NAME -d "$PKG" "Successful install of needed packages ("$PKG")."
+                let not_installed--
+                $S_LOG -d $S_NAME -d "$pkg" "Successful install of needed packages ("$pkg")."
             fi
         fi
     fi
 done
 
-exit $NOT_INSTALLED
+exit $not_installed
